#!/usr/bin/env bash
# Installs the minimal monitoring stack (pinned kube-prometheus-stack) and
# applies the platform dashboard and baseline SLO alerts. Run after Kyverno
# bootstrap so the monitoring namespace exemption is already in place.
# Grafana admin credentials are generated by the chart; fetch them with:
#   kubectl -n monitoring get secret kube-prometheus-stack-grafana \
#     -o jsonpath='{.data.admin-password}' | base64 -d
set -euo pipefail

readonly MONITORING_CHART_VERSION="91.4.1"

kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update prometheus-community
helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
  --namespace monitoring \
  --version "${MONITORING_CHART_VERSION}" \
  -f observability/prometheus-values.yaml \
  --wait \
  --timeout 15m

kubectl create configmap golden-path-overview \
  --namespace monitoring \
  --from-file=golden-path-overview.json=observability/dashboards/golden-path-overview.json \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl -n monitoring label configmap golden-path-overview grafana_dashboard=1 --overwrite
kubectl apply -f observability/prometheus-rules.yaml
kubectl -n monitoring get prometheusrules,configmaps -l grafana_dashboard=1
