apiVersion: platform.example.io/v1alpha1
kind: Service
metadata:
  name: payment-api
spec:
  owner: payments-team
  environment: dev
  contact: payments-team@example.com
  image: 440744245648.dkr.ecr.ap-northeast-1.amazonaws.com/developer-platform-dev/payment-api@sha256:953ef4d7f9522a8f98fab183b67cd9270216379cd00a6b23841554b7739cfcae
  port: 8080
  resources:
    size: small
  availability:
    replicas: 3
  observability:
    enabled: true
  health:
    livenessPath: /healthz
    readinessPath: /readyz
