apiVersion: platform.example.io/v1alpha1
kind: Service
metadata:
  name: payment-api
spec:
  owner: payments-team
  environment: dev
  contact: payments-team@example.com
  image: 440744245648.dkr.ecr.ap-northeast-1.amazonaws.com/developer-platform-dev/payment-api@sha256:b359742b13d36e0574dcfe492f38c6367c2e90c9ed7d0e4c23f6acc6c2fcfe05
  port: 8080
  resources:
    size: small
  availability:
    replicas: 3
  observability:
    enabled: true
  health:
    livenessPath: /healthz
    readinessPath: /readyz
