apiVersion: platform.example.io/v1alpha1
kind: Service
metadata:
  name: payment-api
spec:
  owner: payments-team
  environment: dev
  contact: payments-team@example.com
  image: 440744245648.dkr.ecr.ap-northeast-1.amazonaws.com/developer-platform-dev/payment-api@sha256:d4fa9a4150cf2ebd7240c77945159cd78d53385fa7ed0ec7918475012ea3e647
  port: 8080
  resources:
    size: small
  availability:
    replicas: 3
  observability:
    enabled: true
  health:
    livenessPath: /healthz
    readinessPath: /readyz
